class Autogenerated {
  List<Perfume> perfume;

  Autogenerated({this.perfume});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['Perfume'] != null) {
      perfume = new List<Perfume>();
      json['Perfume'].forEach((v) {
        perfume.add(new Perfume.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.perfume != null) {
      data['Perfume'] = this.perfume.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Perfume {
String name;
  String image;
  String id;
  String gender;
  String makeYear;
  List<String> mainAccords;
  double sentiment;
  double assesment;
  int reviewCount;
  List<String> longevity;
  List<String> sillage;
  String mainPicture;
  List<String> isliked;
  List<String> isMain;
  List<String> isOwned;

  Perfume(
    {this.name,
      this.image,
      this.id,
      this.gender,
      this.makeYear,
      this.mainAccords,
      this.sentiment,
      this.assesment,
      this.reviewCount,
      this.longevity,
      this.sillage,
      this.mainPicture,
      this.isliked,
      this.isMain,
      this.isOwned});

  Perfume.fromJson(Map<String, dynamic> json) {
    name = json['Name'];
    image = json['Image'];
    id = json['id'];
    gender = json['Gender'];
    makeYear = json['MakeYear'];
    mainAccords = json['MainAccords'].cast<String>();
    sentiment = double.parse(json['Sentiment'].toString());
    assesment = double.parse(json['Assesment'].toString());
    reviewCount = json['ReviewCount'];
    longevity = json['Longevity'].cast<String>();
    sillage = json['Sillage'].cast<String>();
    mainPicture = json['MainPicture'];
    isliked = json['isliked'].cast<String>();
    isMain = json['isMain'].cast<String>();
    isOwned = json['isOwned'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Name'] = this.name;
    data['Image'] = this.image;
    data['id'] = this.id;
    data['Gender'] = this.gender;
    data['MakeYear'] = this.makeYear;
    data['MainAccords'] = this.mainAccords;
    data['Sentiment'] = this.sentiment;
    data['Assesment'] = this.assesment;
    data['ReviewCount'] = this.reviewCount;
    data['Longevity'] = this.longevity;
    data['Sillage'] = this.sillage;
    data['MainPicture'] = this.mainPicture;
    data['isliked'] = this.isliked;
    data['isMain'] = this.isMain;
    data['isOwned'] = this.isOwned;
    return data;
  }
}
